kind: pipeline
name: default

steps:
- name: tests_compilation
  image: rikorose/gcc-cmake
  commands:
  - mkdir extras/test/build
  - cd extras/test/build
  - cmake ..
  - make -j32

- name: tests
  image: rikorose/gcc-cmake
  commands:
  - cd extras/test/build
  - ./supladevicetests --gtest_repeat=50 --gtest_shuffle
  depends_on:
  - tests_compilation

- name: esp8266_rtos_compilation_check
  image: devel/esp8266_rtos_sdk
  pull: never
  commands:
  - pwd
  - echo $SUPLA_DEVICE_PATH
  - ls -al
  - export SUPLA_DEVICE_PATH=/drone/src
  - cd extras/examples/esp8266_rtos/
  - rm -f build/supla-esp8266-mk.bin
  - /bin/bash -c "source /supla/esp/ESP8266_RTOS_SDK/export.sh && make -j32"
  - /bin/bash -c "[ -f build/supla-esp8266-mk.bin ] && true || false"

- name: esp_idf_compilation_check
  image: devel/esp-idf
  pull: never
  commands:
  - pwd
  - echo $SUPLA_DEVICE_PATH
  - ls -al
  - export SUPLA_DEVICE_PATH=/drone/src
  - cd extras/examples/esp_idf/
  - rm -f build/supla_esp32.bin
  - /bin/bash -c "source /supla/esp/esp-idf/export.sh && idf.py build"
  - /bin/bash -c "[ -f build/supla_esp32.bin ] && true || false"

- name: freertos_linux_compilation_check
  image: devel/freertos
  pull: never
  commands:
  - pwd
  - echo $SUPLA_DEVICE_PATH
  - ls -al
  - export SUPLA_DEVICE_PATH=/drone/src
  - export SUPLA_FREERTOS_PATH=/supla/FreeRTOS
  - cd extras/examples/freertos_linux
  - rm -f build/supla-freertos-example
  - cmake -B build
  - cmake --build build
  - /bin/bash -c "[ -f build/supla-freertos-example ] && true || false"

- name: linux_compilation_check
# Linux compilation requires generic linux toolset for compilation and building
# which is also part of our freertos docker, so we just reuse it here
  image: devel/freertos
  pull: never
  commands:
  - export SUPLA_DEVICE_PATH=/drone/src
  - cd extras/examples/linux
  - rm -f build/supla-device-linux
  - cmake -B build
  - cmake --build build
  - /bin/bash -c "[ -f build/supla-device-linux ] && true || false"

- name: arduino_esp8266_compilation_check
  image: devel/arduino-cli
  pull: never
  commands:
  - cd examples
  - arduino-cli compile --fqbn esp8266:esp8266:generic --optimize-for-debug --export-binaries --warnings all --clean ./Afore/
  - arduino-cli compile --fqbn esp8266:esp8266:generic --optimize-for-debug --export-binaries --warnings all --clean ./DallasTemperature/
  - arduino-cli compile --fqbn esp8266:esp8266:generic --optimize-for-debug --export-binaries --warnings all --clean ./DHT/
  - arduino-cli compile --fqbn esp8266:esp8266:generic --optimize-for-debug --export-binaries --warnings all --clean ./Fronius/
  - arduino-cli compile --fqbn esp8266:esp8266:generic --optimize-for-debug --export-binaries --warnings all --clean ./GarageParkingAssistLight/
  - arduino-cli compile --fqbn esp8266:esp8266:generic --optimize-for-debug --export-binaries --warnings all --clean ./HC_SR04_Distance_sensor/
  - arduino-cli compile --fqbn esp8266:esp8266:generic --optimize-for-debug --export-binaries --warnings all --clean ./HC_SR04_Distance_sensor_extended/
  - arduino-cli compile --fqbn esp8266:esp8266:generic --optimize-for-debug --export-binaries --warnings all --clean ./ImpulseCounter/
  - arduino-cli compile --fqbn esp8266:esp8266:generic --optimize-for-debug --export-binaries --warnings all --clean ./Pzem_V_2/
  - arduino-cli compile --fqbn esp8266:esp8266:generic --optimize-for-debug --export-binaries --warnings all --clean ./Pzem_V_3/
  - arduino-cli compile --fqbn esp8266:esp8266:generic --optimize-for-debug --export-binaries --warnings all --clean ./RGBW/
  - arduino-cli compile --fqbn esp8266:esp8266:generic --optimize-for-debug --export-binaries --warnings all --clean ./RollerShutter/
  - arduino-cli compile --fqbn esp8266:esp8266:generic --optimize-for-debug --export-binaries --warnings all --clean ./SequenceButton/
  - arduino-cli compile --fqbn esp8266:esp8266:generic --optimize-for-debug --export-binaries --warnings all --clean ./WebInterface/

- name: arduino_esp32_compilation_check
  image: devel/arduino-cli
  pull: never
  commands:
  - cd examples
  - arduino-cli compile --fqbn esp32:esp32:esp32wrover --optimize-for-debug --export-binaries --warnings all --clean ./Afore/
  - arduino-cli compile --fqbn esp32:esp32:esp32wrover --optimize-for-debug --export-binaries --warnings all --clean ./DallasTemperature/
  - arduino-cli compile --fqbn esp32:esp32:esp32wrover --optimize-for-debug --export-binaries --warnings all --clean ./DHT/
  - arduino-cli compile --fqbn esp32:esp32:esp32wrover --optimize-for-debug --export-binaries --warnings all --clean ./Fronius/
  - arduino-cli compile --fqbn esp32:esp32:esp32wrover --optimize-for-debug --export-binaries --warnings all --clean ./GarageParkingAssistLight/
  - arduino-cli compile --fqbn esp32:esp32:esp32wrover --optimize-for-debug --export-binaries --warnings all --clean ./HC_SR04_Distance_sensor/
  - arduino-cli compile --fqbn esp32:esp32:esp32wrover --optimize-for-debug --export-binaries --warnings all --clean ./HC_SR04_Distance_sensor_extended/
  - arduino-cli compile --fqbn esp32:esp32:esp32wrover --optimize-for-debug --export-binaries --warnings all --clean ./ImpulseCounter/
#  - arduino-cli compile --fqbn esp32:esp32:esp32wrover --optimize-for-debug --export-binaries --warnings all --clean ./Pzem_V_2/
#  - arduino-cli compile --fqbn esp32:esp32:esp32wrover --optimize-for-debug --export-binaries --warnings all --clean ./Pzem_V_3/
  - arduino-cli compile --fqbn esp32:esp32:esp32wrover --optimize-for-debug --export-binaries --warnings all --clean ./RGBW/
  - arduino-cli compile --fqbn esp32:esp32:esp32wrover --optimize-for-debug --export-binaries --warnings all --clean ./RollerShutter/
  - arduino-cli compile --fqbn esp32:esp32:esp32wrover --optimize-for-debug --export-binaries --warnings all --clean ./SequenceButton/
  - arduino-cli compile --fqbn esp32:esp32:esp32wrover --optimize-for-debug --export-binaries --warnings all --clean ./WebInterface/

- name: arduino_mega_compilation_check
  image: devel/arduino-cli
  pull: never
  commands:
  - cd examples
  - arduino-cli compile --fqbn arduino:avr:mega --optimize-for-debug --export-binaries --warnings all --clean ./Afore/
  - arduino-cli compile --fqbn arduino:avr:mega --optimize-for-debug --export-binaries --warnings all --clean ./DallasTemperature/
  - arduino-cli compile --fqbn arduino:avr:mega --optimize-for-debug --export-binaries --warnings all --clean ./DHT/
  - arduino-cli compile --fqbn arduino:avr:mega --optimize-for-debug --export-binaries --warnings all --clean ./Fronius/
  - arduino-cli compile --fqbn arduino:avr:mega --optimize-for-debug --export-binaries --warnings all --clean ./GarageParkingAssistLight/
  - arduino-cli compile --fqbn arduino:avr:mega --optimize-for-debug --export-binaries --warnings all --clean ./HC_SR04_Distance_sensor/
  - arduino-cli compile --fqbn arduino:avr:mega --optimize-for-debug --export-binaries --warnings all --clean ./HC_SR04_Distance_sensor_extended/
  - arduino-cli compile --fqbn arduino:avr:mega --optimize-for-debug --export-binaries --warnings all --clean ./ImpulseCounter/
  - arduino-cli compile --fqbn arduino:avr:mega --optimize-for-debug --export-binaries --warnings all --clean ./Pzem_V_2/
  - arduino-cli compile --fqbn arduino:avr:mega --optimize-for-debug --export-binaries --warnings all --clean ./Pzem_V_3/
  - arduino-cli compile --fqbn arduino:avr:mega --optimize-for-debug --export-binaries --warnings all --clean ./RGBW/
  - arduino-cli compile --fqbn arduino:avr:mega --optimize-for-debug --export-binaries --warnings all --clean ./RollerShutter/
  - arduino-cli compile --fqbn arduino:avr:mega --optimize-for-debug --export-binaries --warnings all --clean ./SequenceButton/

- name: rocket
  image: mike1pol/drone-rocket
  settings:
    url:
      from_secret: rocket_url
    user_id:
      from_secret: rocket_user_id
    token:
      from_secret: rocket_token
    channel: github
    avatar_url: "https://miro.medium.com/max/256/0*AqO_2lNemh_Fl9Gm.png"
  when:
    status: [success, failure]
    event:
      exclude:
        - pull_request
  depends_on: [tests, esp8266_rtos_compilation_check, esp_idf_compilation_check,
               freertos_linux_compilation_check,
               arduino_esp32_compilation_check,
               arduino_esp8266_compilation_check,
               arduino_mega_compilation_check
              ]

